# -*- coding: utf-8 -*-
"""Preprocessing Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvIug4mXW8CJ9_zh9c7Pa-iWZjmzD2pK

# Pre-processing Tutorial

## Setup

Run the cell below to import necessary modules.
"""

import numpy as np
import pandas as pd
import requests
from google.colab import drive

"""Connecting to Drive"""

prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

"""Copying paths"""

zillow_path = '/content/drive/My Drive/cis_550_final_proj/datasets/zillow_all_names.csv' # Path to zillow dataset
nces_path = '/content/drive/My Drive/cis_550_final_proj/datasets/NCES_CCD.csv' # Path to life nces dataset in your drive
seda_path = '/content/drive/My Drive/cis_550_final_proj/datasets/seda_school_pool_cs_6.0.csv' # Path to seda dataset in your drive
acs_path = '/content/drive/My Drive/cis_550_final_proj/datasets/acs_zcta.csv' # Path to other dataset in your drive
seda_crosswalk_path = '/content/drive/My Drive/cis_550_final_proj/datasets/seda_crosswalk_6.0.csv'

"""Adding other datasets through URL"""

API_KEY = "330e2a9d072a56732e0232641268ecb2be8047c9"  # api.census.gov/data/key_signup.html
BASE_URL = "https://api.census.gov/data/2024/acs/acs5/profile"
GEO = "zip code tabulation area:*"

# ── DP03: Economic characteristics ────────────────────────────────────────────
dp03_vars = {
    "DP03_0062E": "median_household_income",
    "DP03_0025E": "mean_commute_time",
    "DP03_0009PE": "unemployment_rate",
    "DP03_0119PE": "poverty_rate",
}

r = requests.get(BASE_URL, params={
    "get": ",".join(dp03_vars.keys()) + ",NAME",
    "for": GEO,
    "key": API_KEY
})
dp03 = pd.DataFrame(r.json()[1:], columns=r.json()[0])
dp03 = dp03.rename(columns={**dp03_vars, "zip code tabulation area": "zip_code"})

# ── DP04: Housing characteristics ─────────────────────────────────────────────
dp04_vars = {
    "DP04_0089E": "median_home_value",
    "DP04_0134E": "median_gross_rent",
    "DP04_0002PE": "occupancy_rate",
}

r = requests.get(BASE_URL, params={
    "get": ",".join(dp04_vars.keys()),
    "for": GEO,
    "key": API_KEY
})
dp04 = pd.DataFrame(r.json()[1:], columns=r.json()[0])
dp04 = dp04.rename(columns={**dp04_vars, "zip code tabulation area": "zip_code"})

# ── Merge and save ─────────────────────────────────────────────────────────────
acs_df = dp03.merge(dp04, on="zip_code")
acs_df.to_csv('/content/drive/My Drive/cis_550_final_proj/datasets/acs_zcta.csv', index=False)

print(acs_df.shape)
acs_df.head()

"""# Finally, run the cell below to load the data into a `DataFrames`"""

# Static files from Drive
zillow_df = pd.read_csv(zillow_path)
nces_df = pd.read_csv(nces_path)
seda_df = pd.read_csv(seda_path)
acs_df = pd.read_csv(acs_path)
crosswalk_df = pd.read_csv(seda_crosswalk_path)

# Preview
print(zillow_df.shape, nces_df.shape, seda_df.shape, acs_df.shape, crosswalk_df.shape)
zillow_df.head()

"""# Viewing the dfs for future usage

Zillow
"""

print(zillow_df.shape)
zillow_df.head()

"""National Center for Education Statistics"""

nces_df = pd.read_csv(nces_path)
print(nces_df.shape)  # confirm rows are back

nces_cols = ['NCESSCH', 'SCH_NAME', 'LEA_NAME', 'LCITY', 'LSTATE', 'LZIP',
             'SCH_TYPE_TEXT', 'CHARTER_TEXT', 'GSLO', 'GSHI', 'LEVEL', 'SY_STATUS_TEXT']

nces_df = nces_df[nces_cols]

# Now drop missing only on the critical join/filter columns
nces_df = nces_df.dropna(subset=['NCESSCH', 'LZIP'])

print(nces_df.shape)
nces_df.head()

"""Stanford Education Data Archive"""

print(seda_df.shape)
seda_df.head()

"""Census' American Community Survey"""

print(acs_df.shape)
acs_df.head()

"""Crosswalk"""

print(crosswalk_df.shape)
crosswalk_df.head()

"""## Clean Missing Values

### Remove Rows with Missing Values

First, we generate a dataframe where each element indicates whether that element was missing in the original dataframe.
"""

# Check missing values per dataframe
for name, df in [("zillow", zillow_df), ("nces", nces_df), ("seda", seda_df), ("acs", acs_df), ("crosswalk", crosswalk_df)]:
    missing = df.isnull().sum()
    total_missing = missing.sum()
    print(f"\n{name}: {total_missing} total missing values")
    print(missing[missing > 0])  # only show columns that have missing values

"""Find all rows with at least one missing value, then throw those rows out, then verify nothing is missing anymore."""

# zillow - only drop rows where the most recent month is missing
latest_col = zillow_df.columns[-1]  # last column = most recent month
missing_zillow = zillow_df[latest_col].isnull()
zillow_df = zillow_df.loc[(~missing_zillow).values, :]
zillow_df.isnull().any().any()  # sanity check - should be False for that column

# nces
missing_nces = nces_df.isnull().any(axis=1)
nces_df = nces_df.loc[(~missing_nces).values, :]
nces_df.isnull().any().any()

# seda
missing_seda = seda_df.isnull().any(axis=1)
seda_df = seda_df.loc[(~missing_seda).values, :]
seda_df.isnull().any().any()

# acs
missing_acs = acs_df.isnull().any(axis=1)
acs_df = acs_df.loc[(~missing_acs).values, :]
acs_df.isnull().any().any()

# crosswalk
missing_cw = crosswalk_df.isnull().any(axis=1)
crosswalk_df = crosswalk_df.loc[(~missing_cw).values, :]
crosswalk_df.isnull().any().any()

"""### Drop Rows with any missing values"""

zillow_df    = zillow_df.dropna()
nces_df      = nces_df.dropna()
seda_df      = seda_df.dropna()
acs_df       = acs_df.dropna()
crosswalk_df = crosswalk_df.dropna()

# Sanity check
for name, df in [("zillow", zillow_df), ("nces", nces_df), ("seda", seda_df), ("acs", acs_df), ("crosswalk", crosswalk_df)]:
    print(f"{name}: {df.isnull().any().any()}")  # should all print False

"""## Data Standardization

Making sure that the same data on different datasets is formatted the same way and slim down on some datasets

### 1. Standadize ZIP codes cross datasets
Making sure that they're all same type and zero-padded to 5 digits
"""

zillow_df['RegionName'] = zillow_df['RegionName'].astype(str).str.zfill(5)
acs_df['zip_code'] = acs_df['zip_code'].astype(str).str.zfill(5)
nces_df['LZIP'] = nces_df['LZIP'].astype(str).str.zfill(5)

"""### 2. Standardize NCES IDs across seda/nces/crosswalk
Make sure that they're all the same type
"""

print(seda_df.columns.tolist())
print(crosswalk_df.columns.tolist())

# The crosswalk already has zip codes - so seda joins to crosswalk on sedasch,
# then crosswalk joins to zillow/acs on lzip

# standardize the join keys
seda_df['sedasch'] = seda_df['sedasch'].astype(str)
crosswalk_df['sedasch'] = crosswalk_df['sedasch'].astype(str)
crosswalk_df['ncessch'] = crosswalk_df['ncessch'].astype(str)
nces_df['NCESSCH'] = nces_df['NCESSCH'].astype(str)

# standardize ZIP codes
crosswalk_df['lzip'] = crosswalk_df['lzip'].astype(str).str.zfill(5)
zillow_df['RegionName'] = zillow_df['RegionName'].astype(str).str.zfill(5)
acs_df['zip_code'] = acs_df['zip_code'].astype(str).str.zfill(5)
nces_df['LZIP'] = nces_df['LZIP'].astype(str).str.zfill(5)

# sanity check - how many seda schools match crosswalk
matched = seda_df['sedasch'].isin(crosswalk_df['sedasch'])
print(f"{matched.sum()} / {len(seda_df)} SEDA schools matched to crosswalk")

# sanity check - how many crosswalk zips match zillow
matched_zip = crosswalk_df['lzip'].isin(zillow_df['RegionName'])
print(f"{matched_zip.sum()} / {len(crosswalk_df)} crosswalk ZIPs matched to Zillow")

nces_df['NCESSCH'] = nces_df['NCESSCH'].astype(str)
seda_df['sedasch'] = seda_df['sedasch'].astype(str)
crosswalk_df['sedasch'] = crosswalk_df['sedasch'].astype(str)
crosswalk_df['ncessch'] = crosswalk_df['ncessch'].astype(str)

"""### 3. Check that the join actually works
sanity check
"""

# How many SEDA schools match crosswalk?
matched = seda_df['sedasch'].isin(crosswalk_df['sedasch'])
print(f"{matched.sum()} / {len(seda_df)} SEDA schools matched to crosswalk")

# How many crosswalk NCES IDs match NCES CCD?
matched2 = crosswalk_df['ncessch'].isin(nces_df['NCESSCH'])
print(f"{matched2.sum()} / {len(crosswalk_df)} crosswalk schools matched to NCES")

# How many crosswalk ZIPs match Zillow?
matched3 = crosswalk_df['lzip'].isin(zillow_df['RegionName'])
print(f"{matched3.sum()} / {len(crosswalk_df)} crosswalk ZIPs matched to Zillow")

# How many crosswalk ZIPs match ACS?
matched4 = crosswalk_df['lzip'].isin(acs_df['zip_code'])
print(f"{matched4.sum()} / {len(crosswalk_df)} crosswalk ZIPs matched to ACS")

# Check what the IDs actually look like in each df
print("SEDA sedasch sample:", seda_df['sedasch'].head().tolist())
print("Crosswalk sedasch sample:", crosswalk_df['sedasch'].head().tolist())
print("Crosswalk ncessch sample:", crosswalk_df['ncessch'].head().tolist())
print("NCES NCESSCH sample:", nces_df['NCESSCH'].head().tolist())
print("Crosswalk lzip sample:", crosswalk_df['lzip'].head().tolist())
print("Zillow RegionName sample:", zillow_df['RegionName'].head().tolist())
print("ACS zip_code sample:", acs_df['zip_code'].head().tolist())

"""## Export Data
After cleaning our datasets, resolving entity resolution problems, and choosing indices, we're ready to ingest our the data into our database.

In the past, students have found using Python for data ingestion slow and frustrating, so we won't populate the database here. Instead, we'll export both datasets and the country codes to CSVs. For now we use DataGrip for data ingestion, here are some reference for the [DataGrip DataSource](https://www.jetbrains.com/help/datagrip/managing-data-sources.html)

"""

output_path = '/content/drive/My Drive/cis_550_final_proj/datasets/cleaned/'
import os
os.makedirs(output_path, exist_ok=True)

zillow_df.to_csv(output_path + 'zillow_cleaned.csv', index=False)
nces_df.to_csv(output_path + 'nces_cleaned.csv', index=False)
seda_df.to_csv(output_path + 'seda_cleaned.csv', index=False)
acs_df.to_csv(output_path + 'acs_cleaned.csv', index=False)
crosswalk_df.to_csv(output_path + 'crosswalk_cleaned.csv', index=False)

print("All files saved to Drive.")